### ISSUE TITLE
Issue when both spatie/laravel-blade-x and thepinecode/blade-filters are used

### ISSUE THREAD

**Issue by hmw-michaelr** [spatie/laravel-blade-x#72]
Hi there,

I'm having an issue where if I'm using both spatie/laravel-blade-x and thepinecode/blade-filters.

php artisan commands stop working.

I'm unsure which package is truly the cause here, but hopefully someone might know what might be up.

Here is the log/stacktrace:
`[2019-05-24 10:18:20] local.ERROR: Could not register component 'context' because view 'bladex::context' was not found. {"exception":"[object] (Spatie\\BladeX\\Exceptions\\CouldNotRegisterComponent(code: 0): Could not register component 'context' because view 'bladex::context' was not found. at /home/michael/Documents/Projects/xxx/vendor/spatie/laravel-blade-x/src/Exceptions/CouldNotRegisterComponent.php:12)
[stacktrace]
#0 /home/michael/Documents/Projects/xxx/vendor/spatie/laravel-blade-x/src/BladeX.php(53): Spatie\\BladeX\\Exceptions\\CouldNotRegisterComponent::viewNotFound('bladex::context', 'context')
#1 /home/michael/Documents/Projects/xxx/vendor/spatie/laravel-blade-x/src/BladeXServiceProvider.php(27): Spatie\\BladeX\\BladeX->component('bladex::context', 'context')
#2 [internal function]: Spatie\\BladeX\\BladeXServiceProvider->boot()
#3 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#4 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(817): Illuminate\\Container\\Container->call(Array)
#8 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(800): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\BladeX\\BladeXServiceProvider))
#9 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\BladeX\\BladeXServiceProvider), 29)
#10 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(801): array_walk(Array, Object(Closure))
#11 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#12 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#13 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(322): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#14 /home/michael/Documents/Projects/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#15 /home/michael/Documents/Projects/xxx/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"}
`

**Comment by hmw-michaelr** [comment]
This has been resolved by thepinecode/blade-filters https://github.com/thepinecode/blade-filters/issues/5
